#!/bin/sh
SCRIPT=`readlink -f $0`
TESTDIR=`dirname ${SCRIPT}`
SRCDIR=`dirname ${TESTDIR}`
TOPDIR=`dirname ${SRCDIR}`
#PYARGS=
PYARGS="-W ignore"  # FIXME
${TOPDIR}/runpy ${PYARGS} -m unittest discover -s ${TESTDIR} $*
